import type { Metadata } from "next";
import { Inter, Londrina_Solid, Island_Moments } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "900"],
  variable: "--font-inter",
});
const londrina = Londrina_Solid({
  subsets: ["latin"],
  weight: "900",
  variable: "--font-londrina",
});
const island = Island_Moments({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-island",
});

export const metadata: Metadata = {
  title: "Sandro Luz | Tattoo Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${inter.variable} ${londrina.variable} ${island.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
